# Generated by Django 4.2 on 2023-04-21 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 21, 21, 33, 7, 242351, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
